apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: application-server
  name: application-server
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: application-server
    spec:
      containers:
      - env:
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              key: MONGO_URI
              name: application-server-variables-env
        image: application-server:1.0.0
        name: application-server
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
