# Use root/example as user/password credentials
version: '3.1'

services:
  mongodb:
    image: mongo:4.0.4-xenial
    build: ./mongo
    ports:
      - 27017:27017

  mongo-seed:
    build: ./mongo_seed
    image: mongo-seed:1.0.0
    links:
      - mongodb

  application-server:
    build: .
    image: application-server:1.0.0
    links:
      - mongodb
    ports:
      - 8080:8080
    env_file:
      - variables.env
    depends_on:
      - mongodb
      - mongo-seed

  
